version: "3.8"

services:
  my-postgres:
    image: postgres:latest
    container_name: universe_db
    environment:
      POSTGRES_DB: academy_db 
      POSTGRES_USER: user-dev 
      POSTGRES_PASSWORD: robotics-academy-dev
    ports:
      - "5432:5432"
    volumes:
      - ./RoboticsInfrastructure/database:/universes
      - ./database:/docker-entrypoint-initdb.d
      - ./scripts:/scripts

    robotics-academy:
        image: jderobot/robotics-backend:test
        container_name: developer-container
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        ports:
            - "7164:7164"
            - "7163:7163"
            - "6080:6080"
            - "1108:1108"
        volumes:
            - type: bind
              source: ./
              target: /RoboticsAcademy
        tty: true
        stdin_open: true
        depends_on: 
            - my-postgres
